// This file should be generated by the build system, not edited manually.
#include "pricingengine.hpp"

bool PricingEngine::pricingStrategyCustom(orderBookResponse_t &response,
                                          orderEntryOperation_t &operation)
{
    return false; // Custom strategy not implemented
}