/*
 * Copyright 2021 Xilinx, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


#ifndef XLNX_LINE_HANDLER_ADDRESS_MAP_H
#define XLNX_LINE_HANDLER_ADDRESS_MAP_H




 /* The following are the standard kernel control registers */
#define XLNX_LINE_HANDLER_KERNEL_CONTROL_OFFSET						        (0x00000000)
#define XLNX_LINE_HANDLER_KERNEL_GLOBAL_INTERRUPT_ENABLE_OFFSET		        (0x00000004)
#define XLNX_LINE_HANDLER_KERNEL_IP_INTERRUPT_ENABLE_OFFSET			        (0x00000008)
#define XLNX_LINE_HANDLER_KERNEL_IP_INTERRUPT_STATUS_OFFSET			        (0x0000000C)


/* The following registers are specific to this kernel type */
#define XLNX_LINE_HANDLER_CONFIG_REGISTER_BLOCK_START                       (0x00000010)
#define XLNX_LINE_HANLDER_PORT_MULTIPLIER                                   (0x18)


#define XLNX_LINE_HANDLER_RESET_CONTROL_OFFSET(INPUT_PORT)                  (XLNX_LINE_HANDLER_CONFIG_REGISTER_BLOCK_START + ((INPUT_PORT) * XLNX_LINE_HANLDER_PORT_MULTIPLIER) + 0x00000000)
#define XLNX_LINE_HANDLER_ECHO_DESTINATION_IP_ADDRESS_OFFSET(INPUT_PORT)    (XLNX_LINE_HANDLER_CONFIG_REGISTER_BLOCK_START + ((INPUT_PORT) * XLNX_LINE_HANLDER_PORT_MULTIPLIER) + 0x00000008)
#define XLNX_LINE_HANDLER_ECHO_DESTINATION_PORT_OFFSET(INPUT_PORT)          (XLNX_LINE_HANDLER_CONFIG_REGISTER_BLOCK_START + ((INPUT_PORT) * XLNX_LINE_HANLDER_PORT_MULTIPLIER) + 0x00000010)

#define XLNX_LINE_HANDLER_RESET_SEQUENCE_NUMBER_OFFSET                      (0x00000040)

#define XLNX_LINE_HANDLER_SEQUENCE_RESET_TIMER_OFFSET                       (0x00000048)


#define XLNX_LINE_HANDLER_STATS_RX_WORDS_COUNT_0_OFFSET                     (0x00000050)
#define XLNX_LINE_HANDLER_STATS_RX_META_COUNT_0_OFFSET                      (0x00000060)
#define XLNX_LINE_HANDLER_STATS_DROPPED_WORDS_COUNT_0_OFFSET                (0x00000070)
#define XLNX_LINE_HANDLER_STATS_DEBUG_ADDRESS_0_OFFSET                      (0x00000080)
#define XLNX_LINE_HANDLER_STATS_DEBUG_PORT_0_OFFSET                         (0x00000090)

#define XLNX_LINE_HANDLER_STATS_RX_WORDS_COUNT_1_OFFSET                     (0x000000A0)
#define XLNX_LINE_HANDLER_STATS_RX_META_COUNT_1_OFFSET                      (0x000000B0)
#define XLNX_LINE_HANDLER_STATS_DROPPED_WORDS_COUNT_1_OFFSET                (0x000000C0)
#define XLNX_LINE_HANDLER_STATS_DEBUG_ADDRESS_1_OFFSET                      (0x000000D0)
#define XLNX_LINE_HANDLER_STATS_DEBUG_PORT_1_OFFSET                         (0x000000E0)

#define XLNX_LINE_HANDLER_STATS_TOTAL_PACKETS_SENT_COUNT_OFFSET             (0x000000F0)
#define XLNX_LINE_HANDLER_STATS_TOTAL_WORDS_SENT_COUNT_OFFSET               (0x00000100)
#define XLNX_LINE_HANDLER_STATS_TOTAL_PACKETS_MISSED_COUNT_OFFSET           (0x00000110)

#define XLNX_LINE_HANDLER_STATS_RX_PACKETS_COUNT_0_OFFSET                   (0x00000120)
#define XLNX_LINE_HANDLER_STATS_RX_PACKETS_COUNT_1_OFFSET                   (0x00000130)

#define XLNX_LINE_HANDLER_STATS_ARBITRATED_TX_PACKETS_COUNT_0_OFFSET        (0x00000140)
#define XLNX_LINE_HANDLER_STATS_ARBITRATED_TX_PACKETS_COUNT_1_OFFSET        (0x00000150)

#define XLNX_LINE_HANDLER_STATS_DISCARDED_PACKETS_COUNT_0_OFFSET            (0x00000160)
#define XLNX_LINE_HANDLER_STATS_DISCARDED_PACKETS_COUNT_1_OFFSET            (0x00000170)

#define XLNX_LINE_HANDLER_STATS_CLOCK_TICK_EVENTS_COUNT_OFFSET              (0x00000180)





#define XLNX_LINE_HANDLER_FILTER_DETAILS_START                              (0x00000190)
#define XLNX_LINE_HANDLER_FILTER_DETAILS_MILTIPLIER                         (0xC0)

#define XLNX_LINE_HANDLER_FILTER_SLOT_ADDRESS_OFFSET(INPUT_PORT, SLOT)      (XLNX_LINE_HANDLER_FILTER_DETAILS_START + ((INPUT_PORT) * XLNX_LINE_HANDLER_FILTER_DETAILS_MILTIPLIER) + 0x00000000 + ((SLOT) * 4))
#define XLNX_LINE_HANDLER_FILTER_SLOT_PORT_OFFSET(INPUT_PORT, SLOT)         (XLNX_LINE_HANDLER_FILTER_DETAILS_START + ((INPUT_PORT) * XLNX_LINE_HANDLER_FILTER_DETAILS_MILTIPLIER) + 0x00000040 + ((SLOT) * 4))
#define XLNX_LINE_HANDLER_FILTER_SLOT_SPLIT_ID_OFFSET(INPUT_PORT, SLOT)     (XLNX_LINE_HANDLER_FILTER_DETAILS_START + ((INPUT_PORT) * XLNX_LINE_HANDLER_FILTER_DETAILS_MILTIPLIER) + 0x00000080 + ((SLOT) * 4))











#endif

